id: a94b9cb4324947ff9bc7a51b16895ac7
initial_creation_type: ocr
source_metadata:
  volumes:
    bb44c363a99641c0aad80718304200d9:
      base_file: v061.txt
      image_group_id: I1PD95907
      title: ''
      total_pages: 1557
      volume_number: 62
